// Challenge ID to route name mapping
// This maps challenge IDs from the database to their specific route names

export const CHALLENGE_ROUTES: { [key: string]: string } = {
  '1': 'MorningMeditation',
  '2': 'Exercise',
  '3': 'JournalEntry',
  '4': 'ReadRecoveryMaterial',
  '5': 'CallSupport',
  '6': 'HealthyMeal',
  '7': 'GratitudeList',
  '8': 'ArtCreativeActivity',
  '9': 'NatureWalk',
  '10': 'PracticeMindfulness',
  '11': 'HelpSomeone',
  '12': 'LearnSomethingNew',
  '13': 'MusicTherapy',
  '14': 'HealthySleep',
  '15': 'NoSocialMedia',
  '16': 'StretchYoga',
  '17': 'CookNewRecipe',
  '18': 'WriteAffirmations',
  '19': 'ListenToPodcast',
  '20': 'DeepBreathing',
  '21': 'Complete5KRun',
  '22': 'AttendSupportGroup',
  '23': 'WeekLongChallenge',
  '24': 'MeditationMarathon',
  '25': 'SocialConnection',
};

export const CHALLENGE_DATA: { [key: string]: any } = {
  '1': { title: 'Morning Meditation', desc: 'Start your day with 5 minutes of meditation', diff: 'Easy', points: 15, icon: 'Brain', color: ['#4ECDC4', '#44A08D'] },
  '2': { title: 'Exercise', desc: 'Do 30 minutes of physical activity', diff: 'Medium', points: 20, icon: 'Activity', color: ['#F39C12', '#E67E22'] },
  '3': { title: 'Journal Entry', desc: 'Write in your recovery journal', diff: 'Easy', points: 10, icon: 'BookOpen', color: ['#4ECDC4', '#44A08D'] },
  '4': { title: 'Read Recovery Material', desc: 'Read for 15 minutes about recovery', diff: 'Easy', points: 15, icon: 'Book', color: ['#4ECDC4', '#44A08D'] },
  '5': { title: 'Call Support', desc: 'Reach out to a support person', diff: 'Medium', points: 25, icon: 'Phone', color: ['#F39C12', '#E67E22'] },
  '6': { title: 'Healthy Meal', desc: 'Prepare and eat a nutritious meal', diff: 'Easy', points: 10, icon: 'Utensils', color: ['#4ECDC4', '#44A08D'] },
  '7': { title: 'Gratitude List', desc: 'Write down 3 things you\'re grateful for', diff: 'Easy', points: 10, icon: 'Heart', color: ['#4ECDC4', '#44A08D'] },
  '8': { title: 'Art/Creative Activity', desc: 'Engage in creative expression', diff: 'Easy', points: 15, icon: 'Palette', color: ['#4ECDC4', '#44A08D'] },
  '9': { title: 'Nature Walk', desc: 'Spend 20 minutes outdoors', diff: 'Easy', points: 15, icon: 'TreePine', color: ['#4ECDC4', '#44A08D'] },
  '10': { title: 'Practice Mindfulness', desc: 'Do a 10-minute mindfulness exercise', diff: 'Easy', points: 15, icon: 'Brain', color: ['#4ECDC4', '#44A08D'] },
  '11': { title: 'Help Someone', desc: 'Do something kind for another person', diff: 'Medium', points: 20, icon: 'HandHeart', color: ['#F39C12', '#E67E22'] },
  '12': { title: 'Learn Something New', desc: 'Watch a tutorial or read an article', diff: 'Easy', points: 10, icon: 'GraduationCap', color: ['#4ECDC4', '#44A08D'] },
  '13': { title: 'Music Therapy', desc: 'Listen to uplifting music for 30 minutes', diff: 'Easy', points: 10, icon: 'Music', color: ['#4ECDC4', '#44A08D'] },
  '14': { title: 'Healthy Sleep', desc: 'Get 7-8 hours of sleep', diff: 'Medium', points: 15, icon: 'Moon', color: ['#F39C12', '#E67E22'] },
  '15': { title: 'No Social Media', desc: 'Take a break from social media', diff: 'Medium', points: 10, icon: 'Smartphone', color: ['#F39C12', '#E67E22'] },
  '16': { title: 'Stretch/Yoga', desc: 'Do 15 minutes of stretching or yoga', diff: 'Easy', points: 15, icon: 'Activity', color: ['#4ECDC4', '#44A08D'] },
  '17': { title: 'Cook a New Recipe', desc: 'Try cooking something healthy', diff: 'Medium', points: 15, icon: 'ChefHat', color: ['#F39C12', '#E67E22'] },
  '18': { title: 'Write Affirmations', desc: 'Write 5 positive affirmations', diff: 'Easy', points: 10, icon: 'PenTool', color: ['#4ECDC4', '#44A08D'] },
  '19': { title: 'Listen to Podcast', desc: 'Listen to a recovery or wellness podcast', diff: 'Easy', points: 15, icon: 'Headphones', color: ['#4ECDC4', '#44A08D'] },
  '20': { title: 'Deep Breathing', desc: 'Practice 5 minutes of deep breathing', diff: 'Easy', points: 10, icon: 'Wind', color: ['#4ECDC4', '#44A08D'] },
  '21': { title: 'Complete a 5K Run', desc: 'Run or walk 5 kilometers', diff: 'Hard', points: 50, icon: 'Activity', color: ['#E74C3C', '#C0392B'] },
  '22': { title: 'Attend Support Group', desc: 'Join a recovery support group meeting', diff: 'Medium', points: 40, icon: 'Users', color: ['#F39C12', '#E67E22'] },
  '23': { title: 'Week-Long Challenge', desc: 'Complete 7 days of daily tasks', diff: 'Hard', points: 100, icon: 'Calendar', color: ['#E74C3C', '#C0392B'] },
  '24': { title: 'Meditation Marathon', desc: 'Meditate for 30 minutes straight', diff: 'Hard', points: 45, icon: 'Brain', color: ['#E74C3C', '#C0392B'] },
  '25': { title: 'Social Connection', desc: 'Have a meaningful conversation with a friend', diff: 'Easy', points: 20, icon: 'MessageCircle', color: ['#4ECDC4', '#44A08D'] },
};

