// Challenge Configuration - All 25 challenges with their specific details
export interface ChallengeConfig {
  id: string;
  title: string;
  description: string;
  category: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  points: number;
  // Challenge-specific content
  instructions: string[];
  tips: string[];
  duration?: string;
  steps?: string[];
  motivation?: string;
}

export const CHALLENGES: ChallengeConfig[] = [
  {
    id: 'morning-meditation',
    title: 'Morning Meditation',
    description: 'Start your day with 5 minutes of meditation',
    category: 'wellness',
    difficulty: 'Easy',
    points: 15,
    instructions: [
      'Find a quiet, comfortable place to sit',
      'Set a timer for 5 minutes',
      'Close your eyes and focus on your breath',
      'Let thoughts come and go without judgment',
    ],
    tips: [
      'Try meditating right after waking up',
      'Use a meditation app for guided sessions',
      'Start with just 2-3 minutes if 5 feels too long',
      'Consistency matters more than duration',
    ],
    duration: '5 minutes',
    motivation: 'A calm morning sets the tone for a peaceful day.',
  },
  {
    id: 'exercise',
    title: 'Exercise',
    description: 'Do 30 minutes of physical activity',
    category: 'health',
    difficulty: 'Medium',
    points: 20,
    instructions: [
      'Choose an activity you enjoy (walking, jogging, yoga, etc.)',
      'Warm up for 5 minutes',
      'Exercise for 30 minutes at moderate intensity',
      'Cool down and stretch for 5 minutes',
    ],
    tips: [
      'Start slow and gradually increase intensity',
      'Find an exercise buddy for motivation',
      'Mix different activities to keep it interesting',
      'Listen to music or podcasts while exercising',
    ],
    duration: '30 minutes',
    motivation: 'Your body is your temple - treat it with movement and care.',
  },
  {
    id: 'journal-entry',
    title: 'Journal Entry',
    description: 'Write in your recovery journal',
    category: 'reflection',
    difficulty: 'Easy',
    points: 10,
    instructions: [
      'Set aside 10-15 minutes of quiet time',
      'Write about your thoughts and feelings',
      'Reflect on your progress and challenges',
      'Note what you\'re grateful for today',
    ],
    tips: [
      'Write freely without worrying about grammar',
      'Be honest with yourself',
      'Focus on progress, not perfection',
      'Review past entries to see how far you\'ve come',
    ],
    duration: '10-15 minutes',
    motivation: 'Writing helps process emotions and track your journey.',
  },
  {
    id: 'read-recovery-material',
    title: 'Read Recovery Material',
    description: 'Read for 15 minutes about recovery',
    category: 'education',
    difficulty: 'Easy',
    points: 15,
    instructions: [
      'Choose a recovery book, article, or blog',
      'Set a timer for 15 minutes',
      'Read actively and take notes if helpful',
      'Reflect on what you learned',
    ],
    tips: [
      'Keep recovery materials easily accessible',
      'Join a book club or discussion group',
      'Highlight important passages',
      'Share insights with your support network',
    ],
    duration: '15 minutes',
    motivation: 'Knowledge is power in your recovery journey.',
  },
  {
    id: 'call-support',
    title: 'Call Support',
    description: 'Reach out to a support person',
    category: 'social',
    difficulty: 'Medium',
    points: 25,
    instructions: [
      'Identify someone in your support network',
      'Call or message them',
      'Share how you\'re feeling',
      'Listen to their support and encouragement',
    ],
    tips: [
      'Have a list of support contacts ready',
      'Don\'t wait until you\'re in crisis',
      'Be honest about your struggles',
      'Offer support in return when you can',
    ],
    duration: '10-30 minutes',
    motivation: 'You don\'t have to face this alone - reach out.',
  },
  {
    id: 'healthy-meal',
    title: 'Healthy Meal',
    description: 'Prepare and eat a nutritious meal',
    category: 'health',
    difficulty: 'Easy',
    points: 10,
    instructions: [
      'Plan a balanced meal with protein, vegetables, and whole grains',
      'Prepare the meal mindfully',
      'Eat slowly and savor each bite',
      'Notice how good nutrition makes you feel',
    ],
    tips: [
      'Meal prep on weekends to save time',
      'Try new healthy recipes',
      'Eat with others when possible',
      'Focus on whole, unprocessed foods',
    ],
    duration: '30-60 minutes',
    motivation: 'Nourishing your body is an act of self-care.',
  },
  {
    id: 'gratitude-list',
    title: 'Gratitude List',
    description: 'Write down 3 things you\'re grateful for',
    category: 'reflection',
    difficulty: 'Easy',
    points: 10,
    instructions: [
      'Take a moment to reflect on your day',
      'Write down 3 specific things you\'re grateful for',
      'Be detailed - why are you grateful for each?',
      'Read your list and feel the gratitude',
    ],
    tips: [
      'Try to find new things each day',
      'Include both big and small things',
      'Share your gratitude with others',
      'Keep a gratitude journal',
    ],
    duration: '5 minutes',
    motivation: 'Gratitude shifts your focus from what\'s missing to what\'s present.',
  },
  {
    id: 'art-creative-activity',
    title: 'Art/Creative Activity',
    description: 'Engage in creative expression',
    category: 'wellness',
    difficulty: 'Easy',
    points: 15,
    instructions: [
      'Choose a creative activity (drawing, painting, writing, music, etc.)',
      'Set aside time without distractions',
      'Create without judgment or expectations',
      'Enjoy the process, not just the result',
    ],
    tips: [
      'Try something new if you\'re stuck',
      'Don\'t worry about being "good" at it',
      'Use creativity as emotional expression',
      'Share your creations with others',
    ],
    duration: '20-30 minutes',
    motivation: 'Creativity is a powerful outlet for emotions and stress.',
  },
  {
    id: 'nature-walk',
    title: 'Nature Walk',
    description: 'Spend 20 minutes outdoors',
    category: 'wellness',
    difficulty: 'Easy',
    points: 15,
    instructions: [
      'Go outside to a park, trail, or natural area',
      'Walk at a comfortable pace for 20 minutes',
      'Notice the sights, sounds, and smells around you',
      'Take deep breaths of fresh air',
    ],
    tips: [
      'Leave your phone behind or on silent',
      'Walk in different locations to keep it interesting',
      'Go with a friend or pet',
      'Practice mindfulness while walking',
    ],
    duration: '20 minutes',
    motivation: 'Nature has a calming effect on the mind and body.',
  },
  {
    id: 'practice-mindfulness',
    title: 'Practice Mindfulness',
    description: 'Do a 10-minute mindfulness exercise',
    category: 'wellness',
    difficulty: 'Easy',
    points: 15,
    instructions: [
      'Find a quiet space',
      'Sit comfortably with eyes closed',
      'Focus on your breath or body sensations',
      'When your mind wanders, gently return to your focus',
    ],
    tips: [
      'Use guided mindfulness apps',
      'Start with shorter sessions',
      'Practice at the same time daily',
      'Be patient with yourself',
    ],
    duration: '10 minutes',
    motivation: 'Mindfulness helps you stay present and reduce anxiety.',
  },
  {
    id: 'help-someone',
    title: 'Help Someone',
    description: 'Do something kind for another person',
    category: 'social',
    difficulty: 'Medium',
    points: 20,
    instructions: [
      'Think of someone who could use help',
      'Offer assistance (big or small)',
      'Follow through on your offer',
      'Notice how helping others makes you feel',
    ],
    tips: [
      'Helping others boosts your own mood',
      'Small acts of kindness matter',
      'Volunteer in your community',
      'Help without expecting anything in return',
    ],
    duration: 'Varies',
    motivation: 'Helping others is a powerful way to find purpose and connection.',
  },
  {
    id: 'learn-something-new',
    title: 'Learn Something New',
    description: 'Watch a tutorial or read an article',
    category: 'education',
    difficulty: 'Easy',
    points: 10,
    instructions: [
      'Choose a topic that interests you',
      'Watch a tutorial, read an article, or take an online course',
      'Take notes on what you learn',
      'Try to apply what you learned',
    ],
    tips: [
      'Learn about recovery and mental health',
      'Explore hobbies and interests',
      'Share what you learn with others',
      'Make learning a daily habit',
    ],
    duration: '15-30 minutes',
    motivation: 'Continuous learning keeps your mind engaged and growing.',
  },
  {
    id: 'music-therapy',
    title: 'Music Therapy',
    description: 'Listen to uplifting music for 30 minutes',
    category: 'wellness',
    difficulty: 'Easy',
    points: 10,
    instructions: [
      'Create or choose an uplifting playlist',
      'Find a comfortable place to listen',
      'Focus on the music and let it uplift you',
      'Sing along or move to the music if you feel like it',
    ],
    tips: [
      'Create different playlists for different moods',
      'Discover new uplifting artists',
      'Attend live music events when possible',
      'Music can be a powerful emotional regulator',
    ],
    duration: '30 minutes',
    motivation: 'Music has the power to heal, inspire, and transform your mood.',
  },
  {
    id: 'healthy-sleep',
    title: 'Healthy Sleep',
    description: 'Get 7-8 hours of sleep',
    category: 'health',
    difficulty: 'Medium',
    points: 15,
    instructions: [
      'Set a consistent bedtime and wake time',
      'Create a relaxing bedtime routine',
      'Avoid screens 1 hour before bed',
      'Ensure your bedroom is dark and cool',
    ],
    tips: [
      'Sleep is crucial for recovery',
      'Quality matters as much as quantity',
      'Avoid caffeine and alcohol before bed',
      'Keep a sleep journal to track patterns',
    ],
    duration: '7-8 hours',
    motivation: 'Restorative sleep is essential for physical and mental health.',
  },
  {
    id: 'no-social-media',
    title: 'No Social Media',
    description: 'Take a break from social media',
    category: 'wellness',
    difficulty: 'Medium',
    points: 10,
    instructions: [
      'Delete social media apps from your phone for the day',
      'Use website blockers if needed',
      'Fill the time with other activities',
      'Notice how you feel without constant scrolling',
    ],
    tips: [
      'Start with a few hours, then extend',
      'Use the time for real connections',
      'Social media breaks reduce comparison and anxiety',
      'Focus on the present moment',
    ],
    duration: 'Full day',
    motivation: 'A break from social media can reduce stress and improve mental clarity.',
  },
  {
    id: 'stretch-yoga',
    title: 'Stretch/Yoga',
    description: 'Do 15 minutes of stretching or yoga',
    category: 'health',
    difficulty: 'Easy',
    points: 15,
    instructions: [
      'Find a quiet space with room to move',
      'Follow a yoga video or do your own stretches',
      'Focus on your breath while stretching',
      'Hold each stretch for 20-30 seconds',
    ],
    tips: [
      'Yoga combines movement with mindfulness',
      'Start with beginner-friendly poses',
      'Listen to your body - don\'t push too hard',
      'Make it a daily practice',
    ],
    duration: '15 minutes',
    motivation: 'Stretching and yoga improve flexibility, reduce stress, and connect mind and body.',
  },
  {
    id: 'cook-new-recipe',
    title: 'Cook a New Recipe',
    description: 'Try cooking something healthy',
    category: 'health',
    difficulty: 'Medium',
    points: 15,
    instructions: [
      'Find a healthy recipe you\'ve never tried',
      'Gather all ingredients',
      'Follow the recipe step by step',
      'Enjoy your creation!',
    ],
    tips: [
      'Cooking can be therapeutic and creative',
      'Try recipes from different cuisines',
      'Cook with friends or family',
      'Share your meals with others',
    ],
    duration: '30-60 minutes',
    motivation: 'Cooking new recipes is a form of self-care and creativity.',
  },
  {
    id: 'write-affirmations',
    title: 'Write Affirmations',
    description: 'Write 5 positive affirmations',
    category: 'reflection',
    difficulty: 'Easy',
    points: 10,
    instructions: [
      'Write 5 positive statements about yourself',
      'Make them specific and personal',
      'Write them in present tense',
      'Read them aloud to yourself',
    ],
    tips: [
      'Focus on your strengths and values',
      'Repeat affirmations daily',
      'Place them where you\'ll see them',
      'Believe in what you\'re affirming',
    ],
    duration: '5-10 minutes',
    motivation: 'Positive affirmations rewire your thinking and boost self-confidence.',
  },
  {
    id: 'listen-podcast',
    title: 'Listen to Podcast',
    description: 'Listen to a recovery or wellness podcast',
    category: 'education',
    difficulty: 'Easy',
    points: 15,
    instructions: [
      'Choose a recovery or wellness podcast',
      'Listen actively and take notes',
      'Reflect on what you learned',
      'Share insights with others if helpful',
    ],
    tips: [
      'Listen during walks or commutes',
      'Subscribe to podcasts you enjoy',
      'Take notes on key takeaways',
      'Discuss episodes with friends',
    ],
    duration: '20-60 minutes',
    motivation: 'Podcasts are a great way to learn and feel connected while on the go.',
  },
  {
    id: 'deep-breathing',
    title: 'Deep Breathing',
    description: 'Practice 5 minutes of deep breathing',
    category: 'wellness',
    difficulty: 'Easy',
    points: 10,
    instructions: [
      'Sit or lie down comfortably',
      'Inhale slowly through your nose for 4 counts',
      'Hold your breath for 4 counts',
      'Exhale slowly through your mouth for 6 counts',
      'Repeat for 5 minutes',
    ],
    tips: [
      'Use this technique when feeling anxious',
      'Practice multiple times throughout the day',
      'Focus only on your breath',
      'Deep breathing activates the relaxation response',
    ],
    duration: '5 minutes',
    motivation: 'Deep breathing is a powerful tool to calm your nervous system instantly.',
  },
  {
    id: 'complete-5k-run',
    title: 'Complete a 5K Run',
    description: 'Run or walk 5 kilometers',
    category: 'health',
    difficulty: 'Hard',
    points: 50,
    instructions: [
      'Warm up with 5 minutes of light walking',
      'Run or walk 5 kilometers (3.1 miles)',
      'Maintain a pace that challenges but doesn\'t exhaust you',
      'Cool down and stretch afterward',
    ],
    tips: [
      'Start with walking if you\'re new to running',
      'Use a running app to track distance',
      'Run with a friend for motivation',
      'Celebrate completing the distance!',
    ],
    duration: '30-60 minutes',
    motivation: 'Completing a 5K is a significant achievement that builds confidence and strength.',
  },
  {
    id: 'attend-support-group',
    title: 'Attend Support Group',
    description: 'Join a recovery support group meeting',
    category: 'social',
    difficulty: 'Medium',
    points: 40,
    instructions: [
      'Find a local or online support group',
      'Attend a meeting (in-person or virtual)',
      'Participate and share if comfortable',
      'Listen and support others',
    ],
    tips: [
      'Support groups provide connection and understanding',
      'You\'re not alone in your journey',
      'Regular attendance builds relationships',
      'Both giving and receiving support helps',
    ],
    duration: '60-90 minutes',
    motivation: 'Support groups offer connection, understanding, and hope from people who truly get it.',
  },
  {
    id: 'week-long-challenge',
    title: 'Week-Long Challenge',
    description: 'Complete 7 days of daily tasks',
    category: 'wellness',
    difficulty: 'Hard',
    points: 100,
    instructions: [
      'Commit to completing daily tasks for 7 consecutive days',
      'Track your progress each day',
      'Stay consistent even on difficult days',
      'Celebrate your completion!',
    ],
    tips: [
      'Plan ahead for the week',
      'Set reminders for daily tasks',
      'Focus on one day at a time',
      'This challenge builds discipline and momentum',
    ],
    duration: '7 days',
    motivation: 'Completing a full week of tasks builds incredible momentum and proves your commitment.',
  },
  {
    id: 'meditation-marathon',
    title: 'Meditation Marathon',
    description: 'Meditate for 30 minutes straight',
    category: 'wellness',
    difficulty: 'Hard',
    points: 45,
    instructions: [
      'Find a quiet, comfortable space',
      'Set a timer for 30 minutes',
      'Use guided meditation or focus on your breath',
      'When your mind wanders, gently return to focus',
    ],
    tips: [
      'Build up to 30 minutes gradually',
      'Use meditation apps for guidance',
      'Don\'t judge yourself for wandering thoughts',
      'This is an advanced practice - be patient',
    ],
    duration: '30 minutes',
    motivation: 'A 30-minute meditation is a deep practice that brings profound peace and clarity.',
  },
  {
    id: 'social-connection',
    title: 'Social Connection',
    description: 'Have a meaningful conversation with a friend',
    category: 'social',
    difficulty: 'Easy',
    points: 20,
    instructions: [
      'Reach out to a friend or family member',
      'Have a genuine, meaningful conversation',
      'Listen actively and share authentically',
      'Focus on quality connection over quantity',
    ],
    tips: [
      'Put away distractions during the conversation',
      'Ask meaningful questions',
      'Share your feelings and experiences',
      'Regular connection prevents isolation',
    ],
    duration: '20-30 minutes',
    motivation: 'Meaningful connections are essential for mental health and recovery.',
  },
];

// Helper function to get challenge by ID
export const getChallengeById = (id: string): ChallengeConfig | undefined => {
  return CHALLENGES.find(challenge => challenge.id === id);
};

// Helper function to get challenge by title (for matching with API data)
export const getChallengeByTitle = (title: string): ChallengeConfig | undefined => {
  const normalizedTitle = title.toLowerCase().trim();
  return CHALLENGES.find(challenge => 
    challenge.title.toLowerCase() === normalizedTitle
  );
};

// Mapping from database task names to challenge IDs
const TITLE_TO_ID_MAP: Record<string, string> = {
  'morning meditation': 'morning-meditation',
  'exercise': 'exercise',
  'journal entry': 'journal-entry',
  'read recovery material': 'read-recovery-material',
  'call support': 'call-support',
  'healthy meal': 'healthy-meal',
  'gratitude list': 'gratitude-list',
  'art/creative activity': 'art-creative-activity',
  'nature walk': 'nature-walk',
  'practice mindfulness': 'practice-mindfulness',
  'help someone': 'help-someone',
  'learn something new': 'learn-something-new',
  'music therapy': 'music-therapy',
  'healthy sleep': 'healthy-sleep',
  'no social media': 'no-social-media',
  'stretch/yoga': 'stretch-yoga',
  'cook a new recipe': 'cook-new-recipe',
  'write affirmations': 'write-affirmations',
  'listen to podcast': 'listen-podcast',
  'deep breathing': 'deep-breathing',
  'complete a 5k run': 'complete-5k-run',
  'attend support group': 'attend-support-group',
  'week-long challenge': 'week-long-challenge',
  'meditation marathon': 'meditation-marathon',
  'social connection': 'social-connection',
};

// Get challenge ID from database title
export const getChallengeIdFromTitle = (title: string): string | undefined => {
  const normalizedTitle = title.toLowerCase().trim();
  return TITLE_TO_ID_MAP[normalizedTitle] || 
    CHALLENGES.find(c => c.title.toLowerCase() === normalizedTitle)?.id;
};

